/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { useState, useEffect, useMemo } from "react";
import { 
  ShieldCheck, 
  ShieldAlert, 
  KeyRound, 
  Copy, 
  Check, 
  Lock, 
  RefreshCw, 
  Sliders, 
  HelpCircle, 
  Info, 
  FileText, 
  Terminal, 
  Clock, 
  AlertCircle 
} from "lucide-react";
import { motion, AnimatePresence } from "motion/react";

// --- Types & Interfaces ---
interface DecodedData {
  raw: string;
  decodedString: string;
  decodedJson: any | null;
  error: string | null;
}

interface ClaimsDescription {
  [key: string]: string;
}

// --- Constants ---
const DEFAULT_CLAIMS_DESCRIPTIONS: ClaimsDescription = {
  // RFC 7519 Standard Claims
  iss: "Issuer: Identifies the authority/principal that issued this JWT (often a URL or domain).",
  sub: "Subject: Unique identifier for the subject of this token (e.g. User ID or Account Code).",
  aud: "Audience: Intended recipient of this token (frequently an API identifier or Client ID).",
  exp: "Expiration Time: Timestamp on or after which this token must not be accepted.",
  nbf: "Not Before: Timestamp before which this token must not be active or accepted.",
  iat: "Issued At: Timestamp representing exactly when this token was generated by the compiler.",
  jti: "JWT ID: A unique identifier value for this token, commonly used to prevent duplicate replay attempts.",
  // Custom & common claims
  typ: "Type: Declares the media type of this complete token format (typically 'JWT').",
  alg: "Algorithm: The cryptographic hash algorithm used to sign and check this token payload.",
  kid: "Key ID: A hint pointing to the specific cryptographic public key used to verify the signature.",
  name: "Full Name: Display profile name associated with the authenticated account.",
  email: "Email Address: Verified electronic mail address assigned to this user profile.",
  email_verified: "Email Status: Boolean value indicating if this email account has been verified.",
  roles: "User Roles: Security classification list or access permissions assigned to the token holder.",
  role: "User Role: Core authorization role assigned to this key.",
  scope: "Authorized Scopes: Space-separated OAuth 2.0 capabilities or resource boundaries permitted.",
  picture: "Avatar Image: Public URL linking to the user's uploaded profile picture asset.",
  nickname: "Nickname: Casual display handle or alias for the authenticated profile.",
};

// Standard Example JWT Profiles
const EXAMPLE_TOKENS = {
  auth0: {
    label: "Auth0 User Session",
    desc: "A rich ID token with user email, roles, profile image, and standard OAuth claims.",
    // HS256 with secret "secret"
    token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InNlnMySIn0.eyJzdWIiOiJ1c2VyXzEyMzQ1Njc4OTAiLCJuYW1lIjoiSHVzc2FpbiBDaGFuZGlvIiwiZW1haWwiOiJjaGFuZGlvLmh1c3NhaW4uMDA3QGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbmlzdHJhdG9yIiwiaWF0IjoxNzgxODUzNjAwLCJleHAiOjE4MTMzODk2MDAsImlzcyI6Imh0dHBzOi8vYXV0aC5leGFtcGxlLmNvbSIsImF1ZCI6Imh0dHBzOi8vYXBpLmV4YW1wbGUuY29tIiwicGljdHVyZSI6Imh0dHBzOi8vaW1hZ2VzLnVuc3BsYXNoLmNvbS9waG90by0xNTM0NTI4NzQxNzc1LTRmZmY1NmRjZjI4OSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlfQ.3qJzUuR3x28X_KjM_81Ior10M9N_jZp1gC9jG7v9U-s",
    secret: "secret"
  },
  simple: {
    label: "Minimal OAuth2",
    desc: "A lightweight programmatic access token with a basic scope and audience field.",
    // HS256 with secret "my-app-key"
    token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ODc2NTQzMjEiLCJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJleHAiOjE3ODIyMDAwMDAsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwifQ.lTqL_7oH61Z7Z7AghqH3N5_K7xM0S9p_C2Z2E7v-Z9A",
    secret: "my-app-key"
  },
  expired: {
    label: "Expired Session Token",
    desc: "A token whose expiration timestamp is in the past, triggering live expired warnings.",
    // HS256 with secret "expired-token-key"
    token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJleHBpcmVkX3Nlc3Npb25fdXNlciIsImlhdCI6MTY3MjUzMTIwMCwiZXhwIjoxNzA0MDY3MjAwfQ.jM4T9hU9z5Y7Fchv8Zp0S9h_A2F2q9v-ZgC9X7v-M9A",
    secret: "expired-token-key"
  }
};

export default function App() {
  const [tokenInput, setTokenInput] = useState<string>(EXAMPLE_TOKENS.auth0.token);
  const [hmacSecret, setHmacSecret] = useState<string>(EXAMPLE_TOKENS.auth0.secret);
  const [isBase64Secret, setIsBase64Secret] = useState<boolean>(false);
  
  // Custom click explanation state
  const [hoveredClaim, setHoveredClaim] = useState<string | null>(null);
  const [selectedClaim, setSelectedClaim] = useState<string | null>(null);

  // Clipboard copies
  const [copiedStates, setCopiedStates] = useState<Record<string, boolean>>({
    token: false,
    header: false,
    payload: false,
    signature: false,
  });

  // Crypto state
  const [cryptoStatus, setCryptoStatus] = useState<"VALID" | "INVALID" | "CHECKING" | "UNSUPPORTED">("CHECKING");

  // --- Base64Url Helpers ---
  const base64UrlDecode = (str: string): DecodedData => {
    const response: DecodedData = {
      raw: str,
      decodedString: "",
      decodedJson: null,
      error: null
    };

    if (!str) {
      response.error = "Empty segment";
      return response;
    }

    try {
      // Base64Url validation & formatting
      let base64 = str.replace(/-/g, "+").replace(/_/g, "/");
      const pad = base64.length % 4;
      if (pad) {
        base64 += "=".repeat(4 - pad);
      }

      // Client-side Unicode-safe atob decoding
      const binary = atob(base64);
      const bytes = new Uint8Array(binary.length);
      for (let i = 0; i < binary.length; i++) {
        bytes[i] = binary.charCodeAt(i);
      }
      const decoded = new TextDecoder("utf-8").decode(bytes);
      response.decodedString = decoded;

      try {
        response.decodedJson = JSON.parse(decoded);
      } catch {
        response.decodedJson = null; // Decoded but not native JSON
      }
    } catch {
      response.error = "Invalid Base64Url encoding structure.";
    }

    return response;
  };

  // --- Token Parts Parsing ---
  const tokenParts = useMemo(() => {
    const cleanToken = tokenInput.trim();
    const parts = cleanToken.split(".");
    
    return {
      rawParts: parts,
      count: parts.length,
      header: parts[0] ? base64UrlDecode(parts[0]) : null,
      payload: parts[1] ? base64UrlDecode(parts[1]) : null,
      signature: parts[2] || "",
    };
  }, [tokenInput]);

  // --- Live Clock / Relative Date helpers ---
  const nowUnix = Math.floor(Date.now() / 1000);

  const expStatus = useMemo(() => {
    if (!tokenParts.payload || !tokenParts.payload.decodedJson) return null;
    const exp = tokenParts.payload.decodedJson.exp;
    const iat = tokenParts.payload.decodedJson.iat;
    if (typeof exp !== "number") return null;

    const diff = exp - nowUnix;
    const isExpired = diff <= 0;
    const formattedDate = new Date(exp * 1000).toLocaleString();
    const formattedIat = iat ? new Date(iat * 1000).toLocaleString() : null;

    let relativeText = "";
    const absDiff = Math.abs(diff);
    const m = Math.floor(absDiff / 60);
    const h = Math.floor(m / 60);
    const d = Math.floor(h / 24);

    if (isExpired) {
      if (d > 0) relativeText = `Expired ${d} day${d > 1 ? "s" : ""} ago`;
      else if (h > 0) relativeText = `Expired ${h} hour${h > 1 ? "s" : ""} ago`;
      else if (m > 0) relativeText = `Expired ${m} minute${m > 1 ? "s" : ""} ago`;
      else relativeText = `Expired ${absDiff} second${absDiff > 1 ? "s" : ""} ago`;
    } else {
      if (d > 0) relativeText = `Expires in ${d} day${d > 1 ? "s" : ""}`;
      else if (h > 0) relativeText = `Expires in ${h} hour${h > 1 ? "s" : ""}`;
      else if (m > 0) relativeText = `Expires in ${m} minute${m > 1 ? "s" : ""}`;
      else relativeText = `Expires in ${absDiff} second${absDiff > 1 ? "s" : ""}`;
    }

    return {
      isExpired,
      formattedDate,
      formattedIat,
      relativeText,
      unix: exp,
      timePassedSinceIat: iat ? nowUnix - iat : null
    };
  }, [tokenParts.payload, nowUnix]);

  // --- Real-Time Client-Side Cryptographic Signature Verifier ---
  // Using Web Cryptography API to run completely locally inside browser sandbox
  useEffect(() => {
    let active = true;

    async function verifyToken() {
      // We only support HS256 for real-time local HMAC crypto validation
      const alg = tokenParts.header?.decodedJson?.alg;
      if (!alg) {
        if (active) setCryptoStatus("INVALID");
        return;
      }

      if (alg.toUpperCase() !== "HS256") {
        if (active) setCryptoStatus("UNSUPPORTED"); // RS256, ES256 require public keys
        return;
      }

      const rawSig = tokenParts.signature;
      if (!rawSig || tokenParts.rawParts.length !== 3) {
        if (active) setCryptoStatus("INVALID");
        return;
      }

      if (active) setCryptoStatus("CHECKING");

      try {
        const headerBase64 = tokenParts.rawParts[0];
        const payloadBase64 = tokenParts.rawParts[1];
        
        let keyData: Uint8Array;
        if (isBase64Secret) {
          try {
            const cleanB64 = hmacSecret.replace(/-/g, "+").replace(/_/g, "/");
            const binary = atob(cleanB64);
            keyData = new Uint8Array(binary.length);
            for (let i = 0; i < binary.length; i++) {
              keyData[i] = binary.charCodeAt(i);
            }
          } catch {
            if (active) setCryptoStatus("INVALID");
            return;
          }
        } else {
          keyData = new TextEncoder().encode(hmacSecret);
        }

        const cryptoKey = await window.crypto.subtle.importKey(
          "raw",
          keyData,
          { name: "HMAC", hash: { name: "SHA-256" } },
          false,
          ["sign", "verify"]
        );

        const dataToSign = new TextEncoder().encode(`${headerBase64}.${payloadBase64}`);
        
        // Decode signature (base64url)
        let cleanSig = rawSig.replace(/-/g, "+").replace(/_/g, "/");
        const sigPad = cleanSig.length % 4;
        if (sigPad) cleanSig += "=".repeat(4 - sigPad);
        const binarySig = atob(cleanSig);
        const sigBuffer = new Uint8Array(binarySig.length);
        for (let i = 0; i < binarySig.length; i++) {
          sigBuffer[i] = binarySig.charCodeAt(i);
        }

        const isValid = await window.crypto.subtle.verify(
          "HMAC",
          cryptoKey,
          sigBuffer,
          dataToSign
        );

        if (active) {
          setCryptoStatus(isValid ? "VALID" : "INVALID");
        }
      } catch (err) {
        console.error("Local signature validation failed: ", err);
        if (active) setCryptoStatus("INVALID");
      }
    }

    verifyToken();

    return () => {
      active = false;
    };
  }, [tokenParts, hmacSecret, isBase64Secret]);

  // --- Copy Clipboard helpers ---
  const copyToClipboard = (text: string, type: string) => {
    navigator.clipboard.writeText(text);
    setCopiedStates((prev) => ({ ...prev, [type]: true }));
    setTimeout(() => {
      setCopiedStates((prev) => ({ ...prev, [type]: false }));
    }, 2000);
  };

  // Pre-load default template
  const loadExample = (profileKey: "auth0" | "simple" | "expired") => {
    const profile = EXAMPLE_TOKENS[profileKey];
    setTokenInput(profile.token);
    setHmacSecret(profile.secret);
    setIsBase64Secret(false);
    setSelectedClaim(null);
    setHoveredClaim(null);
  };

  return (
    <div className="ts-page-bg\ min-h-screen\ py-12\ px-4\ sm:px-6\ lg:px-8\ max-w-7xl\ mx-auto" id="jwt-debugger-root">
      
      {/* --- App Header & Descriptive Titles --- */}
      <div className="text-center mb-9" id="app-title-wrapper">
        <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-slate-900/5 border border-slate-900/10 mb-4 text-xs font-medium text-slate-600 shadow-sm">
          <Lock className="w-3.5 h-3.5 text-slate-500 animate-pulse" id="lock-icon" />
          <span>100% Secure Local Sandbox</span>
        </div>
        
        <h1 className="text-4xl sm:text-5xl font-bold tracking-tight text-slate-900 mb-3" id="app-title-header font-display">
          JWT Debugger
        </h1>
        <p className="max-w-2xl mx-auto text-base text-slate-500 font-sans" id="app-description-para">
          Fast, real-time client-side JSON Web Token parser. Decode header structures, explore payload claims, and verify signatures with zero server transmission.
        </p>
      </div>

      {/* --- Quick Profile Selectors --- */}
      <div className="max-w-4xl mx-auto mb-6 bg-white/60 backdrop-blur-sm border border-slate-200/50 rounded-2xl p-4 shadow-sm" id="token-selectors">
        <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2.5">
            <span className="w-2 h-2 rounded-full bg-violet-500 animate-pulse"></span>
            <span className="text-sm font-semibold text-slate-700">Test Profiles:</span>
            <p className="text-xs text-slate-400 hidden md:block">Click to load pre-calculated templates</p>
          </div>
          <div className="flex flex-wrap gap-2 w-full sm:w-auto justify-end">
            {(Object.keys(EXAMPLE_TOKENS) as Array<"auth0" | "simple" | "expired">).map((key) => (
              <button
                key={key}
                onClick={() => loadExample(key)}
                className="text-xs font-medium px-3.5 py-1.5 rounded-lg border border-slate-200 bg-white hover:bg-slate-50 hover:border-slate-300 text-slate-700 shadow-xs cursor-pointer transition-colors duration-150"
                id={`btn-example-${key}`}
              >
                {EXAMPLE_TOKENS[key].label}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* --- Main Apple Glassmorphic Container --- */}
      <div 
        className="mx-auto bg-white/40 backdrop-blur-md border border-white/40 shadow-2xl rounded-3xl overflow-hidden p-6 sm:p-8 max-w-5xl"
        id="main-glass-container"
      >
        
        {/* --- Top Explicit Security Verification Alert --- */}
        <div className="flex items-start gap-3 bg-teal-50/70 border border-teal-200/50 rounded-2xl p-4 mb-8" id="security-assurance-card">
          <ShieldCheck className="w-5 h-5 text-teal-600 shrink-0 mt-0.5" />
          <div>
            <h4 className="text-sm font-bold text-teal-900">Local Sandbox Safe Memory Verification</h4>
            <p className="text-xs text-teal-700 mt-1 leading-relaxed">
              Every operation from token loading to base64url decoding, JSON parsing, and SHA-256 HMAC cryptographic confirmation happens entirely within your web browser. Neither your tokens nor key secrets are ever queried, transmitted, or logged by any network backend. Your secrets remain yours.
            </p>
          </div>
        </div>

        {/* --- Input and Token Separation Layout --- */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 mb-8" id="input-split-section">
          
          {/* Paste Token Area */}
          <div className="lg:col-span-7 flex flex-col" id="textarea-block">
            <div className="flex items-center justify-between mb-2">
              <label className="text-xs font-bold tracking-wider uppercase text-slate-500 flex items-center gap-1.5">
                <Terminal className="w-3.5 h-3.5 text-slate-400" />
                Paste Encoded Token
              </label>
              {tokenInput && (
                <button
                  onClick={() => setTokenInput("")}
                  className="text-xs text-rose-500 hover:text-rose-600 hover:underline flex items-center gap-1 cursor-pointer transition-colors"
                  id="btn-clear"
                >
                  Clear token
                </button>
              )}
            </div>

            <div className="relative group flex-1">
              <textarea
                value={tokenInput}
                onChange={(e) => setTokenInput(e.target.value)}
                placeholder="Paste your base64Url encoded JWT here (header.payload.signature)..."
                className="w-full h-44 sm:h-52 p-4 text-xs font-mono rounded-2xl bg-slate-900 border border-slate-800 text-slate-100 shadow-inner focus:outline-none focus:ring-2 focus:ring-violet-500/50 placeholder-slate-500 resize-none transition-all"
                id="jwt-input-textarea"
                spellCheck="false"
              />
              <button
                onClick={() => copyToClipboard(tokenInput, "token")}
                className="absolute right-3.5 top-3.5 p-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-400 hover:text-slate-200 transition-colors cursor-pointer"
                title="Copy Encoded String"
                id="btn-copy-token"
              >
                {copiedStates.token ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
              </button>
            </div>
          </div>

          {/* Color-Coded Encoded Visualizer Component */}
          <div className="lg:col-span-5 flex flex-col justify-between" id="visualizer-block">
            <div className="mb-2">
              <span className="text-xs font-bold tracking-wider uppercase text-slate-500 block mb-1">
                Parsed Component Color-Key
              </span>
              <p className="text-[11px] text-slate-400">Tokens are split by dots (.) into distinct metadata sections</p>
            </div>

            <div className="h-44 sm:h-52 rounded-2xl bg-slate-50 border border-slate-200/60 p-4 font-mono text-xs overflow-y-auto leading-relaxed break-all select-all flex flex-col justify-between shadow-xs">
              <div>
                {tokenParts.count > 0 && tokenParts.rawParts[0] ? (
                  <span className="text-rose-600 font-semibold bg-rose-50 px-1 py-0.5 rounded border border-rose-100" title="Header part">
                    {tokenParts.rawParts[0]}
                  </span>
                ) : (
                  <span className="text-slate-400 italic">header</span>
                )}
                
                <span className="text-slate-400 font-bold px-0.5">.</span>

                {tokenParts.count > 1 && tokenParts.rawParts[1] ? (
                  <span className="text-violet-600 font-semibold bg-violet-50 px-1 py-0.5 rounded border border-violet-100" title="Payload part">
                    {tokenParts.rawParts[1]}
                  </span>
                ) : (
                  <span className="text-slate-400 italic">payload</span>
                )}

                <span className="text-slate-400 font-bold px-0.5">.</span>

                {tokenParts.count > 2 && tokenParts.rawParts[2] ? (
                  <span className="text-blue-600 font-semibold bg-blue-50 px-1 py-0.5 rounded border border-blue-100" title="Signature part">
                    {tokenParts.rawParts[2]}
                  </span>
                ) : (
                  <span className="text-slate-400 italic">signature</span>
                )}
              </div>

              {/* Status Alert for Incorrect Parts */}
              <div className="pt-3 mt-3 border-t border-slate-205/60 flex items-center justify-between">
                <span className="text-[10px] text-slate-400 font-sans">
                  Structure: {tokenParts.count} of 3 segments parsed
                </span>
                {tokenParts.count !== 3 && (
                  <span className="inline-flex items-center gap-1 text-[11px] font-sans font-medium text-amber-600" id="segment-error-warning">
                    <AlertSquare /> Invalid Format (Requires 3 parts)
                  </span>
                )}
              </div>
            </div>
          </div>

        </div>

        {/* --- Dynamic Validation Status Banners (Active, Expired, Error States) --- */}
        <AnimatePresence mode="wait">
          {expStatus && (
            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className={`p-4 rounded-2xl mb-8 flex flex-col sm:flex-row sm:items-center justify-between gap-3 ${
                expStatus.isExpired 
                  ? "bg-rose-50 border border-rose-200 text-rose-900" 
                  : "bg-indigo-50 border border-indigo-200 text-indigo-900"
              }`}
              id="expiration-status-banner"
            >
              <div className="flex items-center gap-3">
                <Clock className={`w-5 h-5 shrink-0 ${expStatus.isExpired ? "text-rose-500" : "text-indigo-500"}`} />
                <div>
                  <h5 className="text-sm font-bold flex items-center gap-1.5">
                    {expStatus.isExpired ? "Token Session Expired" : "Token Session Active"}
                    <span className={`text-[11px] px-2 py-0.5 rounded-full font-medium ${
                      expStatus.isExpired ? "bg-rose-100 text-rose-800" : "bg-indigo-100 text-indigo-800"
                    }`}>
                      {expStatus.isExpired ? "Invalid" : "Valid"}
                    </span>
                  </h5>
                  <p className="text-xs text-slate-500 mt-0.5">
                    Universal Expiration time: <span className="font-mono">{expStatus.formattedDate}</span> (UTC unix: {expStatus.unix})
                  </p>
                </div>
              </div>
              <div className={`text-xs font-bold font-mono px-3 py-1.5 rounded-lg border flex items-center gap-1.5 ${
                expStatus.isExpired
                  ? "bg-rose-100/50 border-rose-200 text-rose-700"
                  : "bg-indigo-100/50 border-indigo-200 text-indigo-700"
              }`}>
                {expStatus.relativeText}
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* --- PREMIUM APPLE 3-PART GRID LAYOUT --- */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6" id="three-part-jwt-grid">
          
          {/* ====== PART 1: HEADER (RED) ====== */}
          <motion.div 
            className="flex flex-col rounded-2xl border bg-white shadow-xs p-5 transition-all outline-none border-rose-200"
            id="header-bento-card"
            initial={{ opacity: 0, scale: 0.96 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.2, delay: 0.05 }}
          >
            <div className="flex items-center justify-between pb-3 border-b border-rose-100 mb-4">
              <div className="flex items-center gap-2">
                <span className="w-2.5 h-2.5 rounded-full bg-rose-500"></span>
                <h3 className="text-xs font-bold uppercase tracking-wider text-rose-800">
                  Header
                </h3>
              </div>
              <span className="text-[10px] font-mono bg-rose-50 text-rose-700 border border-rose-100 px-2 py-0.5 rounded-md font-medium">
                Metadata
              </span>
            </div>

            {tokenParts.header?.error ? (
              <div className="flex-1 flex flex-col items-center justify-center text-center p-4">
                <AlertCircle className="w-8 h-8 text-rose-400 mb-2" />
                <p className="text-xs font-medium text-rose-700">{tokenParts.header.error}</p>
                <p className="text-[10px] text-slate-400 mt-1">Malformed first element string.</p>
              </div>
            ) : tokenParts.header?.decodedJson ? (
              <div className="flex-1 flex flex-col justify-between min-h-[300px]">
                <div>
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-[11px] text-slate-400">JSON Format</span>
                    <button
                      onClick={() => copyToClipboard(JSON.stringify(tokenParts.header?.decodedJson, null, 2), "header")}
                      className="p-1 rounded hover:bg-rose-50 text-slate-400 hover:text-rose-600 transition-colors cursor-pointer"
                      title="Copy Header JSON"
                      id="btn-copy-header"
                    >
                      {copiedStates.header ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
                    </button>
                  </div>

                  <pre className="p-3.5 bg-rose-50/30 border border-rose-100/60 rounded-xl text-xs font-mono text-slate-800 overflow-x-auto overflow-y-auto max-h-56 leading-relaxed select-all">
                    {JSON.stringify(tokenParts.header.decodedJson, null, 2)}
                  </pre>
                </div>

                {/* Additional metadata helpers */}
                <div className="mt-5 pt-4 border-t border-rose-100">
                  <span className="text-[10px] font-bold uppercase text-rose-800 block mb-2">Algorithm & Type Details</span>
                  <div className="space-y-1.5">
                    <div className="flex items-center justify-between text-xs py-1 px-1.5 rounded-lg bg-rose-50/50">
                      <span className="text-rose-900 font-medium">alg (Algorithm)</span>
                      <span className="font-mono font-semibold text-rose-700">{tokenParts.header.decodedJson.alg || "None"}</span>
                    </div>
                    <div className="flex items-center justify-between text-xs py-1 px-1.5 rounded-lg bg-rose-50/50">
                      <span className="text-rose-900 font-medium">typ (Token Type)</span>
                      <span className="font-mono font-semibold text-rose-700">{tokenParts.header.decodedJson.typ || "None"}</span>
                    </div>
                    {tokenParts.header.decodedJson.kid && (
                      <div className="flex items-center justify-between text-xs py-1 px-1.5 rounded-lg bg-rose-50/50">
                        <span className="text-rose-900 font-medium">kid (Key Hint ID)</span>
                        <span className="font-mono text-[10px] text-rose-700 max-w-[120px] truncate" title={tokenParts.header.decodedJson.kid}>
                          {tokenParts.header.decodedJson.kid}
                        </span>
                      </div>
                    )}
                  </div>
                </div>
              </div>
            ) : (
              <div className="flex-1 flex flex-col items-center justify-center text-center p-8">
                <FileText className="w-10 h-10 text-slate-300 mb-2" />
                <p className="text-xs text-slate-400">Header decoded but doesn't conform to valid JSON format.</p>
                {tokenParts.header?.decodedString && (
                  <pre className="mt-2 text-[10px] font-mono p-2 bg-slate-55 overflow-auto w-full max-h-24">
                    {tokenParts.header.decodedString}
                  </pre>
                )}
              </div>
            )}
          </motion.div>

          {/* ====== PART 2: PAYLOAD (PURPLE) ====== */}
          <motion.div 
            className="flex flex-col rounded-2xl border bg-white shadow-xs p-5 transition-all outline-none border-violet-200"
            id="payload-bento-card"
            initial={{ opacity: 0, scale: 0.96 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.2, delay: 0.1 }}
          >
            <div className="flex items-center justify-between pb-3 border-b border-violet-100 mb-4">
              <div className="flex items-center gap-2">
                <span className="w-2.5 h-2.5 rounded-full bg-violet-500"></span>
                <h3 className="text-xs font-bold uppercase tracking-wider text-violet-800">
                  Payload (Claims)
                </h3>
              </div>
              <span className="text-[10px] font-mono bg-violet-50 text-violet-700 border border-violet-100 px-2 py-0.5 rounded-md font-medium">
                Identity Claims
              </span>
            </div>

            {tokenParts.payload?.error ? (
              <div className="flex-1 flex flex-col items-center justify-center text-center p-4">
                <AlertCircle className="w-8 h-8 text-violet-400 mb-2" />
                <p className="text-xs font-medium text-violet-700">{tokenParts.payload.error}</p>
                <p className="text-[10px] text-slate-400 mt-1">Malformed second element string.</p>
              </div>
            ) : tokenParts.payload?.decodedJson ? (
              <div className="flex-1 flex flex-col justify-between min-h-[300px]">
                <div>
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-[11px] text-slate-400">Claims Object JSON</span>
                    <button
                      onClick={() => copyToClipboard(JSON.stringify(tokenParts.payload?.decodedJson, null, 2), "payload")}
                      className="p-1 rounded hover:bg-violet-50 text-slate-400 hover:text-slate-600 transition-colors cursor-pointer"
                      title="Copy Payload Claims JSON"
                      id="btn-copy-payload"
                    >
                      {copiedStates.payload ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
                    </button>
                  </div>

                  <pre className="p-3.5 bg-violet-50/30 border border-violet-100/60 rounded-xl text-xs font-mono text-slate-800 overflow-y-auto max-h-56 leading-relaxed select-all">
                    {JSON.stringify(tokenParts.payload.decodedJson, null, 2)}
                  </pre>
                </div>

                {/* Interactive Claim Inspector */}
                <div className="mt-5 pt-4 border-t border-violet-100">
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-[10px] font-bold uppercase text-violet-800 block">Interactive Claims Map</span>
                    <span className="text-[9px] text-slate-400 flex items-center gap-0.5"><Info className="w-2.5 h-2.5" /> Hover or Tap keys</span>
                  </div>
                  
                  <div className="flex flex-wrap gap-1.5 max-h-36 overflow-y-auto p-1 bg-slate-50 rounded-xl border border-slate-100">
                    {Object.keys(tokenParts.payload.decodedJson).map((key) => {
                      const value = tokenParts.payload!.decodedJson[key];
                      const isStandard = DEFAULT_CLAIMS_DESCRIPTIONS[key] !== undefined;
                      const isHot = hoveredClaim === key || selectedClaim === key;

                      return (
                        <button
                          key={key}
                          onMouseEnter={() => setHoveredClaim(key)}
                          onMouseLeave={() => setHoveredClaim(null)}
                          onClick={() => setSelectedClaim(selectedClaim === key ? null : key)}
                          className={`text-xs px-2.5 py-1 rounded-lg border font-mono transition-all text-left truncate max-w-full cursor-pointer ${
                            isHot 
                              ? "bg-violet-600 border-violet-700 text-white shadow-xs" 
                              : isStandard 
                                ? "bg-violet-50/50 border-violet-100 text-violet-700 hover:bg-violet-100/60" 
                                : "bg-slate-100 border-slate-200/60 text-slate-600 hover:bg-slate-200/50"
                          }`}
                          id={`btn-claim-${key}`}
                        >
                          <span className="font-semibold">{key}:</span> <span className="text-[10px] opacity-90">{String(value)}</span>
                        </button>
                      );
                    })}
                  </div>

                  {/* Claim Explanatory Card Box */}
                  <div className="mt-2 min-h-[44px]">
                    <AnimatePresence mode="wait">
                      {(hoveredClaim || selectedClaim) ? (
                        <motion.div
                          key={hoveredClaim || selectedClaim || "none"}
                          initial={{ opacity: 0, y: 3 }}
                          animate={{ opacity: 1, y: 0 }}
                          exit={{ opacity: 0, y: -3 }}
                          className="p-2.5 bg-violet-50 border border-violet-100 rounded-lg text-[11px] leading-relaxed text-violet-800 font-sans"
                        >
                          {DEFAULT_CLAIMS_DESCRIPTIONS[hoveredClaim || selectedClaim || ""] || (
                            <span>Custom claim value: <code className="font-mono">{String(tokenParts.payload.decodedJson[hoveredClaim || selectedClaim || ""])}</code>. Used by your specific API or Identity system.</span>
                          )}
                        </motion.div>
                      ) : (
                        <div className="text-[10px] text-slate-400 italic text-center py-2">
                          Select any claim element badge above to decode its RFC specifications.
                        </div>
                      )}
                    </AnimatePresence>
                  </div>
                </div>
              </div>
            ) : (
              <div className="flex-1 flex flex-col items-center justify-center text-center p-8">
                <FileText className="w-10 h-10 text-slate-300 mb-2" />
                <p className="text-xs text-slate-400">Payload decoded but doesn't conform to valid JSON format.</p>
                {tokenParts.payload?.decodedString && (
                  <pre className="mt-2 text-[10px] font-mono p-2 bg-slate-50 overflow-auto w-full max-h-24 text-left select-all">
                    {tokenParts.payload.decodedString}
                  </pre>
                )}
              </div>
            )}
          </motion.div>

          {/* ====== PART 3: SIGNATURE (BLUE) ====== */}
          <motion.div 
            className="flex flex-col rounded-2xl border bg-white shadow-xs p-5 transition-all outline-none border-blue-200"
            id="signature-bento-card"
            initial={{ opacity: 0, scale: 0.96 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.2, delay: 0.15 }}
          >
            <div className="flex items-center justify-between pb-3 border-b border-blue-100 mb-4 font-sans">
              <div className="flex items-center gap-2">
                <span className="w-2.5 h-2.5 rounded-full bg-blue-500"></span>
                <h3 className="text-xs font-bold uppercase tracking-wider text-blue-800">
                  Signature
                </h3>
              </div>
              <span className="text-[10px] font-mono bg-blue-50 text-blue-700 border border-blue-100 px-2 py-0.5 rounded-md font-medium">
                HMAC Verify Check
              </span>
            </div>

            <div className="flex-1 flex flex-col justify-between min-h-[300px]">
              <div>
                <div className="flex items-center justify-between mb-2">
                  <span className="text-[11px] text-slate-400">Cryptographic Hash</span>
                  <button
                    onClick={() => copyToClipboard(tokenParts.signature, "signature")}
                    className="p-1 rounded hover:bg-blue-50 text-slate-400 hover:text-slate-600 transition-colors cursor-pointer"
                    title="Copy Raw Signature"
                    id="btn-copy-signature"
                    disabled={!tokenParts.signature}
                  >
                    {copiedStates.signature ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
                  </button>
                </div>

                {tokenParts.signature ? (
                  <div className="p-3.5 bg-blue-50/30 border border-blue-100/60 rounded-xl text-xs font-mono text-slate-800 break-all leading-normal select-all">
                    {tokenParts.signature}
                  </div>
                ) : (
                  <div className="text-center p-6 bg-slate-50 border border-slate-100 border-dashed rounded-xl text-xs text-slate-400">
                    No signature component detected in the token representation (Unsigned)
                  </div>
                )}
              </div>

              {/* Real-time Crypto verification configuration */}
              <div className="mt-5 pt-4 border-t border-blue-100">
                <span className="text-[10px] font-bold uppercase text-blue-800 block mb-2">
                  Verify HS256 Standard Secret Key
                </span>

                <div className="space-y-3">
                  <div className="flex flex-col gap-1.5">
                    <label className="text-[10px] font-medium text-slate-500">HMAC Secret (Text String)</label>
                    <input
                      type="text"
                      value={hmacSecret}
                      onChange={(e) => setHmacSecret(e.target.value)}
                      placeholder="HMAC Secret (e.g. secret)"
                      className="w-full text-xs font-mono px-3 py-2 rounded-lg bg-white border border-slate-200 focus:outline-none focus:ring-2 focus:ring-blue-500/50 shadow-xs"
                      id="hmac-secret-input"
                    />
                  </div>

                  <div className="flex items-center gap-2">
                    <input
                      type="checkbox"
                      id="base64-secret-checkbox"
                      checked={isBase64Secret}
                      onChange={(e) => setIsBase64Secret(e.target.checked)}
                      className="w-3.5 h-3.5 text-blue-600 border-slate-300 rounded focus:ring-blue-500"
                    />
                    <label htmlFor="base64-secret-checkbox" className="text-[11px] text-slate-600 cursor-pointer">
                      Secret is already base64 encoded
                    </label>
                  </div>

                  {/* Status Indicator Indicator Cards */}
                  <div className="pt-2">
                    <AnimatePresence mode="wait">
                      {cryptoStatus === "VALID" ? (
                        <motion.div 
                          key="valid" 
                          initial={{ opacity: 0, scale: 0.95 }}
                          animate={{ opacity: 1, scale: 1 }}
                          exit={{ opacity: 0, scale: 0.95 }}
                          className="flex items-center gap-2 px-3 py-2 bg-emerald-50 border border-emerald-200 text-emerald-850 rounded-xl"
                        >
                          <ShieldCheck className="w-4 h-4 text-emerald-600 shrink-0" />
                          <span className="text-xs font-bold font-sans">HS256 Signature Verified!</span>
                        </motion.div>
                      ) : cryptoStatus === "INVALID" ? (
                        <motion.div 
                          key="invalid" 
                          initial={{ opacity: 0, scale: 0.95 }}
                          animate={{ opacity: 1, scale: 1 }}
                          exit={{ opacity: 0, scale: 0.95 }}
                          className="flex items-center gap-2 px-3 py-2 bg-rose-50 border border-rose-200 text-rose-850 rounded-xl"
                        >
                          <ShieldAlert className="w-4 h-4 text-rose-500 shrink-0" />
                          <span className="text-xs font-bold font-sans">Signature Verification Failed</span>
                        </motion.div>
                      ) : cryptoStatus === "UNSUPPORTED" ? (
                        <motion.div 
                          key="unsupported" 
                          initial={{ opacity: 0, scale: 0.95 }}
                          animate={{ opacity: 1, scale: 1 }}
                          exit={{ opacity: 0, scale: 0.95 }}
                          className="flex items-center gap-2 px-3 py-2 bg-slate-100 border border-slate-200 text-slate-700 rounded-xl"
                        >
                          <HelpCircle className="w-4 h-4 text-slate-500 shrink-0" />
                          <div className="text-[11px] leading-snug font-sans">
                            <span className="font-bold block text-slate-800">Only HS256 Verified on Page</span>
                            Asymmetric keys (RS256, etc.) cannot be signed cleanly with raw seeds.
                          </div>
                        </motion.div>
                      ) : (
                        <motion.div 
                          key="checking" 
                          className="flex items-center gap-2 px-3 py-2 bg-amber-50 border border-amber-100 text-amber-800 rounded-xl"
                        >
                          <RefreshCw className="w-4 h-4 text-amber-500 animate-spin shrink-0" />
                          <span className="text-xs font-bold font-sans animate-pulse">Calculating Local Verifications...</span>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </div>
                </div>

              </div>
            </div>
          </motion.div>

        </div>

        {/* --- Educational Bottom Summary Block --- */}
        <div className="mt-8 pt-8 border-t border-slate-200/50 max-w-5xl mx-auto" id="app-footer-seal">
          <div className="flex flex-col sm:flex-row items-center justify-between gap-4 text-center sm:text-left text-xs text-slate-400">
            <span className="flex items-center gap-1.5">
              <Lock className="w-3.5 h-3.5 text-slate-400" />
              100% Client-Side Engine â€¢ RFC 7519 Standards Compliant
            </span>
            <div className="flex items-center gap-4">
              <span className="hover:text-slate-600 transition-colors">SHA-256 HMAC Crypto Checksum</span>
              <span className="text-slate-200">|</span>
              <span className="hover:text-slate-600 transition-colors">Unicode UTF-8 Decoder</span>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
}

// Custom simple fallback wrapper in place of alert component
function AlertSquare() {
  return (
    <svg 
      className="w-3.5 h-3.5 shrink-0" 
      viewBox="0 0 24 24" 
      fill="none" 
      stroke="currentColor" 
      strokeWidth="2.5" 
      strokeLinecap="round" 
      strokeLinejoin="round"
    >
      <path d="M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z" />
      <line x1="12" y1="9" x2="12" y2="13" />
      <line x1="12" y1="17" x2="12.01" y2="17" />
    </svg>
  );
}

